sudo: false
language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
      - xsltproc
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
install:
  - ./scripts/setup
script:
  - ./scripts/test
notifications:
  email: false
